Some minor updates

diff --git a/write-dataset b/write-dataset
--- a/write-dataset
+++ b/write-dataset
@@ -1,6 +1,20 @@
 #!/bin/bash
+#
+# Write data to this dataset
 
-source $1/local.sh
+sourcefn=$(readlink -e -- $BASH_SOURCE)
+sourcedir=$(dirname -- $sourcefn)
+errorsig="ERROR: $sourcefn"
+
+if [ -f $1/local.sh ]; then
+    source $1/local.sh 
+elif [ -f ./local.sh ]; then
+    source ./local.sh
+else
+    echo $errorsig
+    echo "Could not find local.sh."
+    exit
+fi
 
 datapath=$DATAPATHS
 sourcepath=$SOURCEPATHS
